export const FETCH_REGISTRATION: 'FETCH_REGISTRATION' = 'FETCH_REGISTRATION';
export const FETCH_REGISTRATION_SUCCESS: 'FETCH_REGISTRATION_SUCCESS' = 'FETCH_REGISTRATION_SUCCESS';
export const FETCH_REGISTRATION_FAIL: 'FETCH_REGISTRATION_FAIL' = 'FETCH_REGISTRATION_FAIL';

export const FETCH_LOGIN: 'FETCH_LOGIN' = 'FETCH_LOGIN';
export const FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS' = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL: 'FETCH_LOGIN_FAIL' = 'FETCH_LOGIN_FAIL';

export const FETCH_USER_DATA: 'FETCH_USER_DATA' = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS' = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL: 'FETCH_USER_DATA_FAIL' = 'FETCH_USER_DATA_FAIL';
export const CANCEL_FETCH_USER_DATA: 'CANCEL_FETCH_USER_DATA' = 'CANCEL_FETCH_USER_DATA';

export const FETCH_USER_UPDATE: 'FETCH_USER_UPDATE' = 'FETCH_USER_UPDATE';
export const FETCH_USER_UPDATE_SUCCESS: 'FETCH_USER_UPDATE_SUCCESS' = 'FETCH_USER_UPDATE_SUCCESS';
export const FETCH_USER_UPDATE_FAIL: 'FETCH_USER_UPDATE_FAIL' = 'FETCH_USER_UPDATE_FAIL';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';
