export const FETCH_INGREDIENTS_LIST = 'FETCH_INGREDIENTS_LIST';
export const FETCH_INGREDIENTS_LIST_SUCCESS = 'FETCH_INGREDIENTS_LIST_SUCCESS';
export const FETCH_INGREDIENTS_LIST_FAIL = 'FETCH_INGREDIENTS_LIST_FAIL';
