export const FETCH_INGREDIENTS_LIST = 'FETCH_INGREDIENTS_LIST';
export const FETCH_INGREDIENTS_LIST_SUCCESS = 'FETCH_INGREDIENTS_LIST_SUCCESS';
export const FETCH_INGREDIENTS_LIST_FAIL = 'FETCH_INGREDIENTS_LIST_FAIL';

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const REMOVE_CURRENT_INGREDIENT = 'REMOVE_CURRENT_INGREDIENT';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REMOVE_BUN = 'REMOVE_BUN';

export const MOVE_INGREDIENTS = 'MOVE_INGREDIENTS';
