export const FETCH_ORDER: 'FETCH_ORDER' = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS' = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL: 'FETCH_ORDER_FAIL' = 'FETCH_ORDER_FAIL';

export const CLOSE_CREATED_ORDER: 'CLOSE_CREATED_ORDER' = 'CLOSE_CREATED_ORDER';
