export const FETCH_OREDER = 'FETCH_OREDER';
export const FETCH_OREDER_SUCCESS = 'FETCH_OREDER_SUCCESS';
export const FETCH_OREDER_FAIL = 'FETCH_OREDER_FAIL';

export const CLOSE_CREATED_ORDER = 'CLOSE_CREATED_ORDER';