export const FETCH_ORDER: 'FETCH_ORDER' = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS' = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL: 'FETCH_ORDER_FAIL' = 'FETCH_ORDER_FAIL';

export const CLOSE_CREATED_ORDER: 'CLOSE_CREATED_ORDER' = 'CLOSE_CREATED_ORDER';

export const CONNECTION_TO_ORDERS_LIST: 'CONNECTION_TO_ORDERS_LIST' = 'CONNECTION_TO_ORDERS_LIST';
export const CONNECTION_TO_ORDERS_LIST_SUCCESS: 'CONNECTION_TO_ORDERS_LIST_SUCCESS' = 'CONNECTION_TO_ORDERS_LIST_SUCCESS';
export const CONNECTION_TO_ORDERS_LIST_FAIL: 'CONNECTION_TO_ORDERS_LIST_FAIL' = 'CONNECTION_TO_ORDERS_LIST_FAIL';
export const GET_DATA_ORDERS_LIST: 'GET_DATA_ORDERS_LIST' = 'GET_DATA_ORDERS_LIST';
export const CLOSE_CONNECTION: 'CLOSE_CONNECTION' = 'CLOSE_CONNECTION';
export const ERROR_CONNECTION: 'ERROR_CONNECTION' = 'ERROR_CONNECTION';
